"""Package-aware forensic extraction for PowerPoint Open XML and PDF files."""

from .extractor import ExtractionError, extract_document, extract_pptx
from .pdf import extract_pdf
from .config import load_dotenv
from .metrics import compute_metrics
from .models import DECKIR_SCHEMA, DECKIR_SCHEMA_VERSION, EVIDENCE_STATUSES, IMAGE_ROLES, DeckIR, ExtractionReport
from .ocr import OcrAdapter, OcrResult, TesseractOcrAdapter, run_ocr
from .diagrams import add_native_diagram_evidence, classify_raster_failure_classes, reconstruct_diagrams, reconstruct_raster_diagrams
from .render import parse_slide_range, render_selected_pdf_pages, render_selected_slides
from .validation import validate_with_openxml_sdk
from .visual import add_native_visual_evidence, classify_image_role, rendered_geometry_evidence
from .evaluation import (
    bbox_iou,
    character_error_rate,
    confidence_calibration,
    evaluate_diagram,
    evaluate_gemini,
    evaluate_image_role,
    evaluate_ocr,
    evaluate_report,
    vision_completeness,
    word_precision_recall,
)
from .vision import GeminiVisionAdapter, VisionAdapter, VisionImage, run_selective_vision, validate_vision_payload
from .output import SEMANTIC_SCHEMA_VERSION, render_markdown, render_semantic_json, semantic_dict
from .evaluator import EVALUATOR_SCHEMA_VERSION, EvaluatorIR, build_evaluator_ir, evaluator_dict, evaluator_json
from .deck_evaluation import (
    DECK_QUALITY_WEIGHT,
    DECK_COMPONENT_WEIGHTS,
    EVALUATION_SCHEMA_VERSION,
    MISSING_EVIDENCE_PENALTY,
    PROPOSAL_COMPONENT_WEIGHTS,
    PROPOSAL_STRENGTH_WEIGHT,
    REVIEW_AREAS,
    REVIEW_DECISIONS,
    RUBRIC_VERSION,
    SCORE_SCALE,
    SEMANTIC_COMPONENTS,
    SEMANTIC_MODEL,
    GeminiSemanticAdapter,
    ProblemStatement,
    ProblemStatementError,
    compute_deterministic_metrics,
    evaluate_deck,
    evaluate_deck_file,
    evaluate_semantics,
    load_deck_ir,
    load_problem_statement,
    validate_problem_statement,
    validate_semantic_payload,
)
from .ranking import (
    BucketThresholds,
    ManifestEntry,
    SubmissionResult,
    assign_ranks,
    bucket_for_score,
    discover_sources,
    download_submission_file,
    infer_ps_id,
    infer_team,
    load_manifest,
    normalize_ps_id,
    rank_submissions,
    render_evaluation_markdown,
    render_ranking_markdown,
)
from .problem_scraper import (
    DEFAULT_SIH_PROBLEM_URL,
    OfficialProblemScraper,
    ProblemScrapeError,
    normalize_problem_id,
    parse_sih_problem_page,
)

__all__ = [
    "DeckIR",
    "DECKIR_SCHEMA",
    "DECKIR_SCHEMA_VERSION",
    "EVIDENCE_STATUSES",
    "IMAGE_ROLES",
    "ExtractionError",
    "ExtractionReport",
    "OcrAdapter",
    "OcrResult",
    "TesseractOcrAdapter",
    "compute_metrics",
    "extract_pptx",
    "extract_pdf",
    "extract_document",
    "add_native_visual_evidence",
    "add_native_diagram_evidence",
    "classify_raster_failure_classes",
    "reconstruct_diagrams",
    "parse_slide_range",
    "rendered_geometry_evidence",
    "render_selected_slides",
    "render_selected_pdf_pages",
    "run_ocr",
    "reconstruct_raster_diagrams",
    "validate_with_openxml_sdk",
    "GeminiVisionAdapter",
    "VisionAdapter",
    "VisionImage",
    "run_selective_vision",
    "validate_vision_payload",
    "SEMANTIC_SCHEMA_VERSION",
    "semantic_dict",
    "render_markdown",
    "render_semantic_json",
    "load_dotenv",
    "classify_image_role",
    "bbox_iou",
    "character_error_rate",
    "confidence_calibration",
    "evaluate_diagram",
    "evaluate_gemini",
    "evaluate_image_role",
    "evaluate_ocr",
    "evaluate_report",
    "vision_completeness",
    "word_precision_recall",
    "EVALUATOR_SCHEMA_VERSION",
    "EvaluatorIR",
    "build_evaluator_ir",
    "evaluator_dict",
    "evaluator_json",
    "EVALUATION_SCHEMA_VERSION",
    "SEMANTIC_MODEL",
    "SEMANTIC_COMPONENTS",
    "PROPOSAL_STRENGTH_WEIGHT",
    "DECK_QUALITY_WEIGHT",
    "PROPOSAL_COMPONENT_WEIGHTS",
    "RUBRIC_VERSION",
    "DECK_COMPONENT_WEIGHTS",
    "MISSING_EVIDENCE_PENALTY",
    "REVIEW_AREAS",
    "REVIEW_DECISIONS",
    "SCORE_SCALE",
    "ProblemStatement",
    "ProblemStatementError",
    "GeminiSemanticAdapter",
    "compute_deterministic_metrics",
    "evaluate_deck",
    "evaluate_deck_file",
    "evaluate_semantics",
    "load_deck_ir",
    "load_problem_statement",
    "validate_problem_statement",
    "validate_semantic_payload",
    "BucketThresholds",
    "ManifestEntry",
    "SubmissionResult",
    "assign_ranks",
    "bucket_for_score",
    "discover_sources",
    "download_submission_file",
    "infer_ps_id",
    "infer_team",
    "load_manifest",
    "normalize_ps_id",
    "rank_submissions",
    "render_evaluation_markdown",
    "render_ranking_markdown",
    "DEFAULT_SIH_PROBLEM_URL",
    "OfficialProblemScraper",
    "ProblemScrapeError",
    "normalize_problem_id",
    "parse_sih_problem_page",
]
